version: '2'
services:
  db:
    image: postgres
    ports:
      - "0:5432"
  redis:
    image: redis
    ports:
      - "0:6379"
  sidekiq:
    build: .
    volumes:
      - .:/multiplayer
    links:
      - db
      - redis
    env_file:
      - .env
    command: bundle exec sidekiq
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/multiplayer
    ports:
      - "32890:3000"
    links:
      - db
      - redis
    env_file:
      - .env