version: '3.7'
services:
  db:
    image: postgres
  redis:
    image: redis
  sidekiq:
    build: .
    volumes:
      - .:/multiplayer
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: bundle exec sidekiq
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/multiplayer
    ports:
      - "32890:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env