version: '2'
services:
  db:
    image: postgres
    ports:
      - "32888:5432"
  web:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/multiplayer
    ports:
      - "32890:3000"
    links:
      - db
    environment:
      DB_HOST: db